require('dotenv').config();
const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
});

async function runSetup() {
    console.log('🌱 Starting SentinelPay Database Setup...');
    
    try {
        console.log('⏳ Creating database tables...');
        const schemaPath = path.join(__dirname, 'schema.sql');
        const schemaSql = fs.readFileSync(schemaPath, 'utf8');
        await pool.query(schemaSql);
        console.log('✅ Tables generated successfully.');

        // clearing prev data if any
        await pool.query('TRUNCATE TABLE ledger_entries, wallets CASCADE;');

        // Insert dummy Wallets funded with $100 each
        console.log('⏳ Seeding dummy wallets...');
        const senderResult = await pool.query(
            "INSERT INTO wallets (balance) VALUES (100.00) RETURNING id;"
        );
        const receiverResult = await pool.query(
            "INSERT INTO wallets (balance) VALUES (100.00) RETURNING id;"
        );

        const senderId = senderResult.rows[0].id;
        const receiverId = receiverResult.rows[0].id;

        console.log(`✅ Created Sender Wallet: ${senderId} ($100.00)`);
        console.log(`✅ Created Receiver Wallet: ${receiverId} ($100.00)`);

        //Appending these fresh UUIDs directly to their local system
        const envPath = path.join(__dirname, '.env');
        const envAppend = `\n\n# Dynamic Test Wallets (Generated by seed.js)\nTEST_SENDER_WALLET_ID=${senderId}\nTEST_RECEIVER_WALLET_ID=${receiverId}\n`;
        
        fs.appendFileSync(envPath, envAppend);
        console.log('📝 Test wallet UUIDs successfully appended to your local .env file!');
        console.log('\n🚀 Setup complete! You can now run your API and execute "node stress.js"');

    } catch (err) {
        console.error('❌ Setup failed:', err.message);
    } finally {
        await pool.end();
    }
}

runSetup();